-- MySQL Script generated by MySQL Workbench
-- Fri Oct 21 10:27:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema municipio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `municipio` ;

-- -----------------------------------------------------
-- Schema municipio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `municipio` ;
SHOW WARNINGS;
USE `municipio` ;

-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) COLLATE 'utf8mb3_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `personas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `personas` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(15) NOT NULL,
  `telefonoMovil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `dni_UNIQUE` ON `personas` (`dni` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `reclamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reclamos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `reclamos` (
  `idReclamo` INT NOT NULL AUTO_INCREMENT,
  `fechaCreacion` VARCHAR(45) NOT NULL,
  `fechaResolucion` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `idCategoria` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idReclamo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(20) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `tipoUsuario` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
